#!/bin/sh
apt-get install -y python-pip
apt-get install python-setuptools
easy_install rsa
pip install hdfs
pip install pyyaml
pip install hash_ring
pip install pymongo
pip install websocket-client
pip install tornado

git clone -b github_unstable https://github.com/younggege/pyblade.git /tmp/pyblade
cd /tmp/pyblade
python setup.py install

git clone -b unstable https://github.com/virtdev/vdtools.git /tmp/vdtools
cd /tmp/vdtools
python setup.py install

rm -rf /tmp/pyblade
rm -rf  /tmp/vdtools
