#!/bin/sh
if [ $# = 0 ]; then
	apt-get install -y python-pip
	apt-get install python-setuptools
	easy_install rsa
	pip install pyyaml
	pip install hash_ring
	pip install pymongo
fi

if [ "$1" = '-i' ]; then
    echo "installing packages for installer"
	apt-get install -y python-pip
	apt-get install python-setuptools
	easy_install rsa
	pip install hash_ring
	
    if [ -e /tmp/vdtools ]; then
	  rm -rf /tmp/vdtools
	fi
	git clone -b unstable https://github.com/virtdev/vdtools.git /tmp/vdtools
	cd /tmp/vdtools
	python setup.py install
fi

if [ "$1" = '-b' ]; then
    echo "installing packages for backend"
	apt-get install -y python-pip
	apt-get install python-setuptools
	easy_install rsa
	pip install pyyaml
	pip install pymongo
	pip install hash_ring
	
	if [ -e /tmp/pyblade ]; then
	  rm -rf /tmp/pyblade
	fi
	git clone -b github_unstable https://github.com/younggege/pyblade.git /tmp/pyblade
	cd /tmp/pyblade
	python setup.py install
fi

if [ "$1" = '-m' ]; then
    echo "installing packages for manager"
	apt-get install -y python-pip
	apt-get install python-setuptools
	easy_install rsa
	pip install pyyaml
	pip install hash_ring
	pip install websocket-client
	pip install tornado
fi

if [ "$1" = '-r' ]; then
    echo "installing packages for repository"
	apt-get install -y python-pip
	apt-get install python-setuptools
	easy_install rsa
	pip install hdfs
	pip install pymongo
	pip install hash_ring
fi

