#!/usr/bin/python

import sys
import argparse

if __name__ ==  '__main__': 
    parser = argparse.ArgumentParser()
    parser.add_argument('-b', '--backend', action='store_true')
    parser.add_argument('-i', '--installer', action='store_true')
    parser.add_argument('-m', '--manager', action='store_true')
    parser.add_argument('-r', '--repository', action='store_true')
    
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit()
        
    args = parser.parse_args(sys.argv[1:])
    if args.backend:
        import rsa
        import yaml
        import pyblade
        import pymongo
        import hash_ring
    
    elif args.installer:
        import rsa
        import vdtools
        import hash_ring
    
    elif args.manager:
        import rsa
        import yaml
        import tornado
        import hash_ring
        import websocket
    
    elif args.repository:
        import rsa
        import hdfs
        import pymongo
        import hash_ring
    
    else:
        parser.print_help()