LOG_DEBUG = True
LOG_ERROR = True

HDFS = True
DEBUG = True
SHOW_TIME = False
MANAGER_WEBSOCKET = True

MONGO_PORT = 27017
FRONTEND_PORT = 9001
BACKEND_PORT = 9002
REPOSITORY_PORT = 9003
INSTALLER_PORT = 9004
ALLOCATOR_PORT = 9005
RECORDER_PORT = 9006
HDFS_PORT = 50070
FTP_PORT = 21

PKG_MAX = 65536 # Bytes
MANAGER_PORTS = [10001]
IFACE = 'lo'

FRONTEND = True
BACKEND = True
MANAGER = True
REPOSITORY = True
INSTALLER = True
ALLOCATOR = True
RECORDER = True
 