LOG_DRIVER = True
LOG_APP = False

LOG_REPOSITORY = True
LOG_RECORDER = True
LOG_MANAGER = True
LOG_FRONTEND = False
LOG_BACKEND = True
LOG_ALLOCATOR = True

LOG_USER = False
LOG_HDFSCLIENT = True
LOG_FTPCLIENT = False
LOG_DPMSERVER = False
LOG_DB = False