SERVER_DATABASE = []

SERVER_FRONTEND = []
SERVER_BACKEND = []
SERVER_REPO = []
SERVER_ALLOC = []
SERVER_RECORDER =  []
SERVER_MANAGER = []
SERVER_UPLOADER = []

SERVER_APPDB = []
SERVER_REPODB = []
SERVER_ALLOCDB = []
